# Generated by Django 4.2.6 on 2023-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='starting_date',
            field=models.DateField(blank=True),
        ),
    ]
